apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: cinesentiment-backend
  namespace: cinesentiment
spec:
  host: cinesentiment-backend
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 100
      http:
        h2UpgradePolicy: UPGRADE
        http1MaxPendingRequests: 50
    loadBalancer:
      simple: ROUND_ROBIN
    outlierDetection:
      consecutive5xxErrors: 3
      interval: 30s
      baseEjectionTime: 30s
  subsets:
    - name: v1
      labels:
        version: v1
