apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: cinesentiment-gateway
  namespace: cinesentiment
  labels:
    app: cinesentiment
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - cinesentiment.local
        - "*.cinesentiment.local"
