"""
Precompute ROC + threshold curves for Insights page (fast subsample).
Merges into artifacts/results/evaluation.json and writes insights_curves.json.

Run: python scripts/generate_insights_curves.py
     make insights-curves
"""
from __future__ import annotations

import json
import sys
from datetime import datetime, timezone
from pathlib import Path

import numpy as np
from transformers import AutoModelForSequenceClassification, AutoTokenizer

PROJECT_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT_ROOT))

from backend.ml_core import (  # noqa: E402
    ARTIFACTS_DIR,
    calibration_curve_points,
    default_test_path,
    default_val_path,
    has_trained_weights,
    load_evaluation_artifact,
    pr_curve_points,
    predict_probs,
    read_labeled_csv,
    roc_curve_points,
    sanitize_for_json,
    save_evaluation_artifact,
    threshold_curve_points,
)

MODEL_DIR = PROJECT_ROOT / "sentiment_model"
MAX_ROWS = 2000


def curves_for_split(model, tokenizer, split: str):
    path = default_val_path() if split == "val" else default_test_path()
    texts, y_true = read_labeled_csv(path, max_rows=MAX_ROWS)
    y_prob = predict_probs(model, tokenizer, texts)
    return {
        "threshold_curve": threshold_curve_points(y_true, y_prob),
        "roc_curve": roc_curve_points(y_true, y_prob),
        "pr_curve": pr_curve_points(y_true, y_prob),
        "calibration_curve": calibration_curve_points(y_true, y_prob),
        "n_samples": len(texts),
        "split": split,
    }


def main():
    if not has_trained_weights(MODEL_DIR):
        raise SystemExit(f"No weights in {MODEL_DIR}. Train first or set HUB_MODEL_FALLBACK.")

    tokenizer = AutoTokenizer.from_pretrained(MODEL_DIR)
    model = AutoModelForSequenceClassification.from_pretrained(MODEL_DIR)

    artifact = load_evaluation_artifact() or {}
    curves = artifact.get("curves") or {}

    for split in ("val", "test"):
        path = default_val_path() if split == "val" else default_test_path()
        if not path.is_file():
            print(f"Skip missing: {path}")
            continue
        print(f"Computing curves for {split} (max {MAX_ROWS} rows)...")
        block = curves_for_split(model, tokenizer, split)
        curves[split] = {
            "threshold_curve": block["threshold_curve"],
            "roc_curve": block["roc_curve"],
            "pr_curve": block["pr_curve"],
            "calibration_curve": block["calibration_curve"],
            "n_samples": block["n_samples"],
        }
        cal = block["calibration_curve"]
        print(
            f"  n={block['n_samples']} auc={block['roc_curve'].get('auc')} "
            f"ap={block['pr_curve'].get('average_precision')} "
            f"brier={cal.get('brier_score')} ece={cal.get('ece')}"
        )

    artifact["curves"] = curves
    artifact["insights_generated_at"] = datetime.now(timezone.utc).isoformat()
    save_evaluation_artifact(artifact)

    out = ARTIFACTS_DIR / "insights_curves.json"
    out.parent.mkdir(parents=True, exist_ok=True)
    payload = {
        "generated_at": artifact["insights_generated_at"],
        "max_rows_per_split": MAX_ROWS,
        "splits": curves,
    }
    payload = sanitize_for_json(payload)
    out.write_text(json.dumps(payload, indent=2, allow_nan=False), encoding="utf-8")
    print(f"Wrote {out}")

    cal_payload = sanitize_for_json(
        {
            "generated_at": artifact["insights_generated_at"],
            "max_rows_per_split": MAX_ROWS,
            "splits": {
                name: curves[name]["calibration_curve"]
                for name in curves
                if "calibration_curve" in curves[name]
            },
        }
    )
    cal_out = ARTIFACTS_DIR / "calibration.json"
    cal_out.write_text(json.dumps(cal_payload, indent=2, allow_nan=False), encoding="utf-8")
    print(f"Wrote {cal_out}")

    frontend_data = PROJECT_ROOT / "frontend" / "data"
    frontend_data.mkdir(parents=True, exist_ok=True)
    (frontend_data / "calibration.json").write_text(
        json.dumps(cal_payload, indent=2, allow_nan=False), encoding="utf-8"
    )
    js_bundle = (
        "// Auto-generated by make insights-curves — bundled calibration fallback\n"
        "window.CINESENTIMENT_CALIBRATION = "
        + json.dumps(cal_payload, indent=2, allow_nan=False)
        + ";\n"
    )
    (frontend_data / "calibration-data.js").write_text(js_bundle, encoding="utf-8")
    print(f"Wrote {frontend_data / 'calibration.json'} and calibration-data.js")


if __name__ == "__main__":
    main()
